[tool.ruff]
select = ["F", "E", "W", "I"] # F: Pyflakes, E/W: pycodestyle, I: isort
ignore = []
line-length = 88 
target-version = "py310"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # Ignore unused imports int __init__

[tool.mypy]
files = ["src/"]
disable_error_code = ["arg-type"]
strict = true

[[tool.mypy.overrides]]
module = "psycopg2.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.infrastructure.db.*"
disable_error_code = ["no-untyped-call"]
